import Head from 'next/head'
import { getSession } from 'next-auth/react';
import { NextPageContext } from 'next';
import React from 'react';
import Navbar from '@/components/Navbar';
import TaskList from '@/components/TaskList';

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: '/auth',
        permanent: false,
      }
    }
  }

  return {
    props: {}
  }
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <header className='flex flex-col items-center justify-center align-middle text-4xl mt-10 font-medium'>Welcome To Task Manager</header>
      <TaskList />
    </>
  )
}
